# File for deployment from Docker to Google Cloud
# With build
name: Google Cloud Deploy

# Defines what branch the yaml file will activate on
on:
  push:
    branches: [ main ]

# Jobs tab:
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Part for the Google Cloud image configuration, pulled from git secret keys
    - uses: google-github-actions/setup-gcloud@v1 # Update to v1
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}  # Use secrets for project ID too
        export_default_credentials: true

     # Creating a docker image from current dir
    - name: Build Docker Image
      run: docker build -t test-image:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet

  # Push the image to conatiner registry on google cloud
    - name: Push Docker Image to Container Registry (GCR)
      env:
        GIT_TAG: v0.1.0
      run: |-
        docker tag test-image:latest gcr.io/${{secrets.GCP_PROJECTS_ID}}/test-image:latest
        docker tag test-image:latest gcr.io/${{secrets.GCP_PROJECTS_ID}}/test-image:$GIT_TAG
        docker push gcr.io/${{secrets.GCP_PROJECT_ID}}/test-image:latest
        docker push gcr.io/${{secrets.GCP_PROJECT_ID}}/test-image:$GIT_TAG