# File for deployment from Docker to Google Cloud
# With build
name: Google Cloud Deploy

# Defines what branch the yaml file will activate on
on:
  push:
    branches: [ main ]

# Jobs tab:

jobs:
  route_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 
      # Version of the action for setting up python, not Python Version
        uses: actions/setup-python@v5
        with:
            # Semantic version range syntax or exact version of a python version
          python-version: '3.12.x'
      # Installs the requirements of the file
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Testing code with pytest
      - name: Test with pytest
        run: | 
          pip install pytest pytest-cov
          pytest tests





jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: cicd-test-436421
      IMAGE_NAME: test-image

    steps:
    - name: Checkout
      uses: actions/checkout@v4


    # Authenticate to google cloud was never authenticated
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

    # Part for the Google Cloud image configuration, pulled from git secret keys
    - uses: google-github-actions/setup-gcloud@v1 # Update to v1
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}  # Use secrets for project ID too
        export_default_credentials: true

     # Creating a docker image from current dir
    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet

  # Push the image to conatiner registry on google cloud
    - name: Push Docker Image to Container Registry (GCR)
      # Fo some rea
      env:
        GIT_TAG: v0.1.0
      run: |-
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/test-image:latest
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/test-image:$GIT_TAG
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG