# File for deployment from Docker to Google Cloud
# With build
name: Google Cloud Deploy

# Defines what branch the yaml file will activate on
on:
  push:
    branches: [ main ]

# Jobs tab:
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Part for the Google Cloud image configuration, pulled from git secret keys
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}  # Use secrets for project ID too
        export_default_credentials: true

    # Creating a Docker image from current dir
    - name: Build Docker Image
      run: docker build -t ${{ secrets.IMAGE_NAME }}:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet

    # Push the image to container registry on Google Cloud
    - name: Push Docker Image to Container Registry (GCR)
      env:
        GIT_TAG: v0.1.0
      run: |-
        docker tag ${{ secrets.IMAGE_NAME }}:latest gcr.io/${{ secrets.GCP_PROJECT_ID }}/{{ secrets.IMAGE_NAME }}:latest
        docker tag ${{ secrets.IMAGE_NAME }}:latest gcr.io/${{ secrets.GCP_PROJECT_ID }}/{{ secrets.IMAGE_NAME }}:$GIT_TAG
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/{{ secrets.IMAGE_NAME }}:latest
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/{{ secrets.IMAGE_NAME }}:$GIT_TAG
